name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      APP_NAME: jenkins-to-github-actions
      ENVIRONMENT: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Groovy
        run: |
          sudo apt-get update
          sudo apt-get install -y groovy

      - name: Check Groovy installation
        run: |
          which groovy
          groovy --version

      - name: Validate inputs and repo structure
        run: |
          chmod +x scripts/ValidateInputs.groovy
          groovy scripts/ValidateInputs.groovy

      - name: Build
        run: |
          chmod +x scripts/build.sh
          scripts/build.sh

      - name: Test
        run: |
          chmod +x scripts/test.sh
          scripts/test.sh
